# Generated by Django 4.0.4 on 2022-05-05 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Baocaongay',
            fields=[
                ('ngay', models.DateField(primary_key=True, serialize=False)),
                ('tongthu', models.DecimalField(decimal_places=2, max_digits=13)),
                ('tongchi', models.DecimalField(decimal_places=2, max_digits=13)),
                ('chechlechthuchi', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
            options={
                'db_table': 'baocaongay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Baocaothang',
            fields=[
                ('ngaythang', models.DateField(primary_key=True, serialize=False)),
                ('phieugoi', models.IntegerField()),
                ('phieudong', models.IntegerField()),
                ('chenhlechdonggoi', models.IntegerField()),
            ],
            options={
                'db_table': 'baocaothang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chucnang',
            fields=[
                ('macn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tencn', models.CharField(max_length=20)),
                ('tenmanhinhduocloat', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'chucnang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HelloWorldChoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField()),
            ],
            options={
                'db_table': 'hello_world_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HelloWorldQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('time_published', models.DateTimeField()),
            ],
            options={
                'db_table': 'hello_world_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('makh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenkh', models.CharField(max_length=50)),
                ('diachi', models.CharField(max_length=50)),
                ('cccd', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'khachhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaitietkiem',
            fields=[
                ('maltk', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ltk', models.CharField(max_length=20)),
                ('kyhan', models.IntegerField()),
                ('sotiengoitoithieu', models.DecimalField(decimal_places=2, max_digits=13)),
                ('thoigiangoitoithieu', models.IntegerField()),
                ('laisuat', models.FloatField()),
            ],
            options={
                'db_table': 'loaitietkiem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('tendn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('matkhau', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nguoidung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nhomnguoidung',
            fields=[
                ('tennhom', models.CharField(max_length=50)),
                ('manhom', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nhomnguoidung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieuruttien',
            fields=[
                ('maprt', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngayrut', models.DateField(blank=True, null=True)),
                ('sotienrut', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
            options={
                'db_table': 'phieuruttien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieutietkiem',
            fields=[
                ('maptk', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sotiengoi', models.DecimalField(decimal_places=2, max_digits=13)),
                ('ngaydongphieu', models.DateField(blank=True, null=True)),
                ('ngaymophieu', models.DateField()),
                ('sodu', models.DecimalField(decimal_places=2, max_digits=13)),
                ('tinhtrang', models.IntegerField()),
            ],
            options={
                'db_table': 'phieutietkiem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phanquyen',
            fields=[
                ('macn', models.OneToOneField(db_column='macn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='admin_site.chucnang')),
            ],
            options={
                'db_table': 'phanquyen',
                'managed': False,
            },
        ),
    ]
