# Generated by Django 4.0.4 on 2022-05-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_remove_usersextendclass_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorldChoice',
        ),
        migrations.DeleteModel(
            name='HelloWorldQuestion',
        ),
    ]
